  CREATE TABLE "EBA_DEMO_CHART_EMP" 
   (	"EMPNO" NUMBER(4,0) NOT NULL ENABLE, 
	"ENAME" VARCHAR2(10), 
	"JOB" VARCHAR2(9), 
	"MGR" NUMBER(4,0), 
	"HIREDATE" DATE, 
	"SAL" NUMBER(7,2), 
	"COMM" NUMBER(7,2), 
	"DEPTNO" NUMBER(2,0), 
	"CREATED_BY" VARCHAR2(100),
	"CREATED_ON" DATE,
	"UPDATED_BY" VARCHAR2(100),
	"UPDATED_ON" DATE,
	 CONSTRAINT "EBA_DEMO_CHART_EMP_PK" PRIMARY KEY ("EMPNO")
  USING INDEX  ENABLE
   ) ;